#!/usr/bin/env python
import rospy
import roslib
from geometry_msgs.msg import PoseWithCovarianceStamped

FREQUENCY = 10

if __name__ == '__main__':
    print("initializing poses")
    rospy.init_node('robot_poses')
    turtlename = rospy.get_param('~turtle')
    x = rospy.get_param('~x_pos')
    y = rospy.get_param('~y_pos')
    z = rospy.get_param('~z_pos')
    rate = rospy.Rate(FREQUENCY)
    pub = rospy.Publisher('/%s/initialpose' % turtlename, PoseWithCovarianceStamped, queue_size=1)
    message = PoseWithCovarianceStamped()
    while not rospy.is_shutdown():
        message.pose.pose.position.x = x
        message.pose.pose.position.y = y
        message.pose.pose.position.z = z
        message.pose.pose.orientation.x = 0
        message.pose.pose.orientation.y = 0
        message.pose.pose.orientation.z = 0
        message.pose.pose.orientation.w = 1
        pub.publish(message)
        rate.sleep()
